# Docker compose file for building the local hosting environment
#   - Builds the nginx container specified in Docker/app/Dockerfile
#   - Builds the mysql database container
#
# @author   Alan Cortes
# @version  1.0.0
#

name: nginx-mysql-env

services:
    app:
        build:
            context: ./Docker/app
        container_name: app
        depends_on:
            - db
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d/
            - ./vhosts:/home/admin/web/
        ports:
            - "8080:80"
        environment:
            - NGINX_PORT=80
    db:
        image: mysql:latest
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: secretpassword
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
